server:
  port: 20001
  # 在返回给页面的结果里，把错误信息添加到message里
  error:
    include-message: always

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: coupon-customer-serv
  datasource:
    # mysql数据源
    url: jdbc:mysql://127.0.0.1:3306/coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: qwe`123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: CloudCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
#    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
#    properties:
#      hibernate.show_sql: true
#      hibernate.format_sql: true
    open-in-view: false
  cloud:
    nacos:
      discovery:
        #Nacos服务地址，可以配置多个，用 ,分隔
        server-addr: localhost:8848
        #注册到Nacos上的服务名称
        service: coupon-customer-serv
        #客户端（各个微服务）向Nacos发送心跳的时间，单位是毫秒
        heart-beat-interval: 5000
        #心跳检测的超时时间，一定要大于heart-beat-interval时间
        heart-beat-timeout: 20000
        #元数据---可以自己随便定制
        metadata:
          myData: qwe
        #命名空间ID，进行数据隔离
        namespace: dev
        #两个服务如果要调用，一定要在同一个group
        group: myGroup
        #以下非必须，
        register-enabled: true
        #宕机后重启是否优先使用本地缓存
        naming-load-cache-at-start: false
        username: nacos
        password: nacos
    sleuth:
      sampler:
        probability: 1
        rate: 1000
    zipkin:
      sender:
        type: web
        base-url: http://localhost:9411/
#  openfeign:
#    client:
#      default-config:
#      config:
#        coupon-template-feign-client:
#          connectTimeout: 2000
#          readTimeout: 3000
#          loggerLevel: full
#        coupon-calculation-feign-client:
#          connectTimeout: 2000
#          readTimeout: 3000
#          loggerLevel: full
#    circuitBreaker:
#      hystrix:
#        enable: true
#      metrics:
#        healthSnapshot:
#          intervalInMilliseconds: 5000 # 健康快照间隔时间设置为 5 秒

logging:
  level:
    com.litao.coupon: debug
    com.litao.coupon.customer.feign.TemplateService: debug
    com.litao.coupon.customer.feign.CalculationService: debug

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 2000
      coupon_template-serv:
        connectTimeout: 1000
        readTimeout: 1500
  circuitbreaker:
    enabled: true



